export const categories = [
  "Adega",
  "Açaí",
  "Bar",
  "Cafeteria",
  "Conveniência",
  "Culinária japonesa",
  "Doceria",
  "Hamburgueria",
  "Marmitaria",
  "Padaria",
  "Pastelaria",
  "Pizzaria",
  "Salgado",
  "Sorveteria",
] as const;
